# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$golang\
$python\
[ ➜ ](bold bg:#9DB17C fg:#034172) \
"""

right_format = '''$status $cmd_duration'''

[directory]
truncation_length = 8
truncation_symbol = '…/'
format = '[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)'
style = "bold bg:#9DB17C fg:#034172"

[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = " "
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = 'bg:#24292F fg:#ffffff'

[git_state]
format = '[ \($state( $progress_current/$progress_total)\) ]($style)'
style = 'bg:#24292F'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '([ \[$all_status$ahead_behind\] ]($style))'
style = 'bg:#24292F fg:#da3633'

[golang]
symbol = " "
style = "bg:#292829 fg:#00a89e"
format = '[ $symbol($version )]($style)'

[python]
symbol = " "
style = "bg:#4584b6 fg:#ffde57"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[status]
format = '[$symbol]($style) '
success_symbol = ' ✅'
map_symbol = true
disabled = false
